Feature/contacts
ProkoptsovD/icecream-website-project pull request #1
Opened 2022-01-27 09:16 UTC by Iryna-Holova

Добавила разметку, посмотри пожалуйста. Секцию решила назвать Локации, так как контакты в каждой локации свои, а секция все же о локациях. Если это ок то поменяй названия паршалов с contacts на locations. Спасибо)

P.S. в scss файле contacts забыл нижнее подчеркивание, думаю лучше тебе самому добавить, боюсь наломать)))

2022-01-27 10:29 UTC, ProkoptsovD commented on src/partials/contacts.html
> +          <li class="locations__contacts--item">
locations__contacts--item - так задумано, что используется символ '--' модификатора? Или опечатка?

2022-01-27 10:30 UTC, ProkoptsovD commented on src/partials/contacts.html
> +          <li class="locations__contacts--item">
Тут тоже locations__contacts--item - так задумано, что используется символ '--' модификатора? Или опечатка?

2022-01-27 10:32 UTC, ProkoptsovD commented on src/partials/contacts.html
> +        <p class="locations__type">CAFE</p>
тип заведения, то есть Cafe нужно писать по нормам языка: первая буква заглавная, потом строчные. А если все нужно в верхнем регистре, просто в CSS задать тексту свойство toUpperCase

2022-01-27 10:33 UTC, ProkoptsovD commented on src/partials/contacts.html
> +        <p class="locations__type">FOODTRUCK</p>
тип заведения, то есть Foodtruck нужно писать по нормам языка: первая буква заглавная, потом строчные. А если все нужно в верхнем регистре, просто в CSS задать тексту свойство toUpperCase

2022-01-27 10:33 UTC, ProkoptsovD commented on src/partials/contacts.html
> +        <p class="locations__type">CAFE</p>
тип заведения, то есть Cafe нужно писать по нормам языка: первая буква заглавная, потом строчные. А если все нужно в верхнем регистре, просто в CSS задать тексту свойство toUpperCase

2022-01-27 10:35 UTC, ProkoptsovD commented on src/partials/contacts.html
> +      <li class="restaurans__button">Our Locations</li>
В <li> должна быть еще кнопка <buttons type="button">

2022-01-27 10:36 UTC, ProkoptsovD commented on src/partials/contacts.html
> +      <li class="restaurans__button">Franchise</li>
Тоже самое: в `li` должна быть еще кнопка `buttons type="button"`

2022-01-27 10:46 UTC, ProkoptsovD commented on src/partials/contacts.html
> +            <p class="locations__working-time">06:00 AM - 10:00 PM</p>
и все часы работы лучше оберyть в тег `time`. Вот так `<time datetime="06:00">06:00 AM</time> - <time datetime="10:00">10:00 PM</time>`

2022-01-27 10:48 UTC, ProkoptsovD requested changes
Ира, внеси пожалуйста, эти правки

2022-01-27 11:25 UTC, Iryna-Holova commented on src/partials/contacts.html
> +          <li class="locations__contacts--item">
опечатка, сдалаю

2022-01-27 11:25 UTC, Iryna-Holova commented on src/partials/contacts.html
> +          <li class="locations__contacts--item">
опечатка, сдалаю

2022-01-27 11:32 UTC, Iryna-Holova commented on src/partials/contacts.html
> +        <p class="locations__type">CAFE</p>
Не в курсе что прям запрещено в html писать большими буквами. Зато знаю что текст должен быть скопирован из макета. Точно нужно менять на маленькие? это странно) 
в CSS конечно сделала бы text-transform в любом случае...

2022-01-27 11:32 UTC, Iryna-Holova commented on src/partials/contacts.html
> +        <p class="locations__type">FOODTRUCK</p>
Не в курсе что прям запрещено в html писать большими буквами. Зато знаю что текст должен быть скопирован из макета. Точно нужно менять на маленькие? это странно)
в CSS конечно сделала бы text-transform в любом случае...

2022-01-27 11:32 UTC, Iryna-Holova commented on src/partials/contacts.html
> +        <p class="locations__type">CAFE</p>
Не в курсе что прям запрещено в html писать большими буквами. Зато знаю что текст должен быть скопирован из макета. Точно нужно менять на маленькие? это странно)
в CSS конечно сделала бы text-transform в любом случае...

2022-01-27 11:33 UTC, Iryna-Holova commented on src/partials/contacts.html
> +      <li class="restaurans__button">Our Locations</li>
это фиаско), исправлю позор вечером

2022-01-27 11:33 UTC, Iryna-Holova commented on src/partials/contacts.html
> +      <li class="restaurans__button">Franchise</li>
это фиаско), исправлю позор вечером

2022-01-27 11:39 UTC, Iryna-Holova commented on src/partials/contacts.html
> +            <p class="locations__working-time">06:00 AM - 10:00 PM</p>
я тоже так планировала, но погуляла по сайтам сетей ресторанов, чтобы посмотреть как люди это делают. И на удивление не встретила ни одного datetime. Решила не делать. Настаиваешь?

2022-01-27 12:16 UTC, Iryna-Holova commented on src/partials/contacts.html
> +        <p class="locations__type">CAFE</p>
Тоже кстати прошлась по мощным сайтам, много где встретила большие буквы в коде. Но в общем как скажешь, босс)

2022-01-27 14:54 UTC, ProkoptsovD commented on src/partials/contacts.html
> +        <p class="locations__type">CAFE</p>
Я чего-то был уверен, что текст нельзя, чтобы был в верхнем регистре, где-то в материалах из конспекта читал. Нашел такую с статью https://web-standards.ru/articles/text-transform-and-copy/ . Короче, маякни если не изменяла, я тогда сделаю аппрув

2022-01-27 14:55 UTC, ProkoptsovD commented on src/partials/contacts.html
> +        <p class="locations__type">FOODTRUCK</p>
смотри выше и маякуй))

2022-01-27 14:55 UTC, ProkoptsovD commented on src/partials/contacts.html
> +        <p class="locations__type">CAFE</p>
смотри выше и маякуй

2022-01-27 14:56 UTC, ProkoptsovD commented on src/partials/contacts.html
> +      <li class="restaurans__button">Our Locations</li>
все окей

2022-01-27 14:56 UTC, ProkoptsovD commented on src/partials/contacts.html
> +      <li class="restaurans__button">Franchise</li>
все окей

2022-01-27 14:59 UTC, ProkoptsovD commented on src/partials/contacts.html
> +            <p class="locations__working-time">06:00 AM - 10:00 PM</p>
В нашем конспекте написано буквально следующее: **Человек увидит понятный текст, а ассистивная технология прочитает атрибут datetime и получит точное значение в нужном формате**. Считаю, что лучше сделать наш сайт более доступным, но не настаиваю. Тоже подумай, как лучше. Большие сайты не показатель. Есть много сайтов чисто на дивах, но мы, тем не мене, верстаем согласно стандартам HTML5, то есть семантично

2022-01-27 21:03 UTC, Iryna-Holova commented
проверь плиииз. все сделала, большие буквы оставила)

2022-01-28 09:04 UTC, ProkoptsovD approved these changes

2022-01-28 09:04 UTC, merged