Feature/about
ProkoptsovD/icecream-website-project pull request #4
Opened 2022-01-27 14:50 UTC by AlonaObidenko

2022-01-27 15:25 UTC, ProkoptsovD commented on src/partials/about.html
> +            <img src="images/pitcher & cow/pitcher & cow-desktop-x1.png" alt="A transparent pitcher of milk in front of black and white cow and motto 'bio eco'" width="516" height="516">
в имени картинки не должно быть пробелов) только нижнее подчеркивание или дефис

2022-01-27 15:26 UTC, ProkoptsovD commented on src/partials/about.html
> +            <img src="images/pitcher & cow/pitcher & cow-desktop-x1.png" alt="A transparent pitcher of milk in front of black and white cow and motto 'bio eco'" width="516" height="516">
описание сильно длинное и непонятное) раз это контентное изображение, то лучше написать типа **cow and pitcher with milk**

2022-01-27 15:29 UTC, ProkoptsovD commented on src/partials/about.html
> +                    ./images/pitcher & cow/pitcher & cow-desktop-x3.png 3x
Сергей сказал, что 2х будет достаточно

2022-01-27 15:30 UTC, ProkoptsovD commented on src/partials/about.html
> +            <h3 class="about__subtitle">Fusce ut velit laoreet, tempus arcu eu, molestie tortor. Nam vel justo cursus, faucibus lorem eget, egestas eros. Maecenas eleifend erat at justo fringilla.</h
и здесь лучше сделать `p`, потому что заголовок всегда короткий, а тут просто текст, выделенный жирным

2022-01-27 15:31 UTC, ProkoptsovD commented on src/partials/about.html
> +            <img src="images/pitcher & cow/pitcher & cow-desktop-x1.png" alt="A transparent pitcher of milk in front of black and white cow and motto 'bio eco'" width="516" height="516">
а будет картинка с брызгами молока, которые по бокам от коровы?

2022-01-27 15:32 UTC, ProkoptsovD requested changes
чутка нужно исправить)

2022-01-27 19:58 UTC, AlonaObidenko commented on src/partials/about.html
> +            <img src="images/pitcher & cow/pitcher & cow-desktop-x1.png" alt="A transparent pitcher of milk in front of black and white cow and motto 'bio eco'" width="516" height="516">
> в имени картинки не должно быть пробелов) только нижнее подчеркивание или дефис

справді, вилетіло з голови🙈🙈🙈

2022-01-27 19:59 UTC, AlonaObidenko commented on src/partials/about.html
> +            <img src="images/pitcher & cow/pitcher & cow-desktop-x1.png" alt="A transparent pitcher of milk in front of black and white cow and motto 'bio eco'" width="516" height="516">
> а будет картинка с брызгами молока, которые по бокам от коровы?

для десктопа і моб версії скачала і оптимізувала, планшет чекаю на вказівки

2022-01-27 20:00 UTC, AlonaObidenko commented on src/partials/about.html
> +            <img src="images/pitcher & cow/pitcher & cow-desktop-x1.png" alt="A transparent pitcher of milk in front of black and white cow and motto 'bio eco'" width="516" height="516">
зауваження виправила

2022-01-27 20:01 UTC, AlonaObidenko commented on src/partials/about.html
> +                    ./images/pitcher & cow/pitcher & cow-desktop-x3.png 3x
ок, зайве(3х) видалила

2022-01-27 20:01 UTC, AlonaObidenko commented on src/partials/about.html
> +            <h3 class="about__subtitle">Fusce ut velit laoreet, tempus arcu eu, molestie tortor. Nam vel justo cursus, faucibus lorem eget, egestas eros. Maecenas eleifend erat at justo fringilla.</h
виправила

2022-01-27 20:02 UTC, AlonaObidenko commented
> чутка нужно исправить)

зроблено)

2022-01-28 09:02 UTC, ProkoptsovD approved these changes

2022-01-28 09:02 UTC, merged