add html hero and header
ProkoptsovD/icecream-website-project pull request #5
Opened 2022-01-27 15:51 UTC by MariaZhuk

2022-01-27 16:06 UTC, ProkoptsovD commented on src/partials/hero-header.html
> +                <img src="images/table/tasty.png" alt="Девушка ест мороженное в рожке">
Надо сделать описание в `alt`  на английском

2022-01-27 16:08 UTC, ProkoptsovD commented on src/partials/hero-header.html
> +                <source srcset="" media="" sizes="" type="images/png">
нужно всего один `<source srcset="" media="" type="images/png">` без `sizes="" `, а все картинки перечислить с путями к картинке через запятую в `srcset=""`

2022-01-27 16:11 UTC, ProkoptsovD commented on src/partials/hero-header.html
> +                    <a class="hero__link" href="#">Products</a>
на линки в навигации надо поставить в `href="#products"` и так далее по списку секций, чтобы работали как якоря, а потом в заголовки секций добавим `id="products"` и сайт будет прокручивать нас к нужному разделу

2022-01-27 16:12 UTC, ProkoptsovD commented on src/partials/hero-header.html
> +                    <nav class="nav-header">
почему два раза тег `<nav>`?

2022-01-27 16:13 UTC, ProkoptsovD commented on src/partials/hero-header.html
> +        <ul class="establishments">
списком будет хорошо)

2022-01-27 16:14 UTC, ProkoptsovD requested changes
все хорошо, но нужно чуть подправить

2022-01-27 16:34 UTC, MariaZhuk commented on src/partials/hero-header.html
> +                    <a class="hero__link" href="#">Products</a>
Про якоря помню, сделаю

2022-01-27 16:35 UTC, MariaZhuk commented on src/partials/hero-header.html
> +        <ul class="establishments">
Принято

2022-01-27 16:35 UTC, MariaZhuk commented on src/partials/hero-header.html
> +                <img src="images/table/tasty.png" alt="Девушка ест мороженное в рожке">
Перепишу

2022-01-27 16:39 UTC, MariaZhuk commented on src/partials/hero-header.html
> +                    <nav class="nav-header">
Второй это отдельный нав который попадает в мобильное меню. У меня так было в домашке. НО по логике мне кажется что тот нав что идет перед лого можно убрать. Что скажешь?

2022-01-27 16:51 UTC, MariaZhuk commented on src/partials/hero-header.html
> +                <source srcset="" media="" sizes="" type="images/png">
Может тогда сделаем через Дискриптор w? На подобии этого
<img
  srcset="photo-300.jpg 300w, photo-600.jpg 600w, photo-1200.jpg 1200w"
  src="photo-300.jpg"
  alt="Описание изображения для всех версий"
/>

2022-01-27 17:07 UTC, ProkoptsovD commented on src/partials/hero-header.html
> +                <source srcset="" media="" sizes="" type="images/png">
на собрании общем же договорились через Х

2022-01-27 17:14 UTC, ProkoptsovD commented on src/partials/hero-header.html
> +                    <nav class="nav-header">
да, думаю, что нав перед лого можно убрать.

2022-01-27 17:16 UTC, MariaZhuk commented on src/partials/hero-header.html
> +                <source srcset="" media="" sizes="" type="images/png">
Думала дать больше вводных для браузера) Ок, делаю через x)

2022-01-27 17:16 UTC, MariaZhuk commented on src/partials/hero-header.html
> +                    <nav class="nav-header">
Принято

2022-01-28 08:58 UTC, ProkoptsovD commented on src/partials/hero-header.html
> +                <img srcset="images/table/milk.png 1x, images/table/milk@2x.png 2x, images/desktop/milk188.png 1x, images/desktop/milk376@2x.png 2x"
Мария, здесь нет картинки для мобилки 2х. И поправь меня, если ошибаюсь, но вроде нужно сначала в `srcset` указывать десктоп, потом таблетку и в конце идет мобилка

2022-01-28 08:59 UTC, ProkoptsovD requested changes
надо посмотреть порядок перечисления картинок для разных девайсов

2022-01-28 10:18 UTC, ProkoptsovD approved these changes

2022-01-28 10:25 UTC, merged