feature/product
ProkoptsovD/icecream-website-project pull request #6
Opened 2022-01-27 20:30 UTC by Mariianath

Добавлена разметка и классы.
Где классов нет- есть подобные элементы на стр, нужен общий класс.

2022-01-27 20:47 UTC, Iryna-Holova commented on src/partials/products.html
> +<section id="products"class="product-section">
пробела нет между якорем и классом

2022-01-28 09:08 UTC, ProkoptsovD commented on src/partials/products.html
> +    <div class="product-box container">
заголовок и подзаголовок и все карточки должны быть в одном общем `div` с классом `container`. А сам блок продуктов должен быть обернуть в тег `section`

2022-01-28 09:09 UTC, ProkoptsovD requested changes
чуть-чуть исправить разметку

2022-01-28 10:16 UTC, ProkoptsovD commented on src/partials/products.html
> +<section id="products"class="product-section">
спасибо) сказал)

2022-01-28 16:55 UTC, ProkoptsovD approved these changes

2022-01-28 16:55 UTC, merged